### ISSUE TITLE
reactionnerd: "unrecoverable error"

### ISSUE THREAD

**Issue by Morkxy** [naparuba/shinken#1170]
Hi,

This night at 1h AM, my reactionnerd is crushed.
What other informations can i send to help ?
=> i use Shinken 2.0 RC2 on Debian 7.4 and this is my stack log:

```
2014-03-30 01:02:20,923 [1396137740] Warning : [reactionner-spartacus] The worker 128 goes down unexpectedly!
2014-03-30 01:02:20,979 [1396137740] Critical : I got an unrecoverable error. I have to exit
2014-03-30 01:02:20,979 [1396137740] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
2014-03-30 01:02:21,000 [1396137741] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/satellite.py", line 991, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 261, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/satellite.py", line 783, in do_loop_turn
    self.adjust_worker_number_by_load()
  File "/usr/local/lib/python2.7/dist-packages/shinken/satellite.py", line 544, in adjust_worker_number_by_load
    self.create_and_launch_worker(module_name=mod)
  File "/usr/local/lib/python2.7/dist-packages/shinken/satellite.py", line 403, in create_and_launch_worker
    q = self.manager.Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 673, in temp
    dispatch(conn, None, 'decref', (token.id,))
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 105, in dispatch
    raise convert_to_error(kind, result)
RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 207, in handle_request
    result = func(c, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 435, in decref
    assert self.id_to_refcount[ident] >= 1
KeyError: '1060f38'
```

Thank you :)

**Comment by Deepakonze** [comment]
[1449738116] HOST ALERT: dlink;DOWN;SOFT;1;PING CRITICAL - Packet loss = 100%

[1449738418] HOST ALERT: dlink;DOWN;HARD;2;PING CRITICAL - Packet loss = 100%

[1449738418] HOST NOTIFICATION: admin;dlink;DOWN;notify-host-by-email;PING CRITICAL - Packet loss = 100%

[1449738421] WARNING: [Shinken] The notification command '/var/lib/shinken/libexec/notify_by_email.py -n host -S localhost -r XXXX@abc.com -f html -c "PROBLEM,,dlink,,192.168.2.2,,Thu 10 Dec 14:36:58 IST 2015"" -o ""DOWN,,00h 05m 01s"' raised an error (exit code=1): 'Traceback (most recent call last):'

Please help me this error.
