### ISSUE TITLE
Bug with acknowledgment and accent 

### ISSUE THREAD

**Issue by Caez83** [naparuba/shinken#1324]
I have a bug with Shinken 2.0.x.
Problem with the WebUI or thruk 
Test with Sqlite and Mongodb retention 

When i would like to add an acknowledgment i have an error if their accent.

Exemple 1:
My user have an accent in his alias 
Alias: Sébastien
Problem: The user can't acknowledge service

Exemple 2:
Aknowledgement comment: traité
Problem: No user can acknowledge the service with this comment

If an user have no accent in his alias and if i don't put accent on the comment, their is no problem.
I don't have this problem with shinken 1.x 

Error in the broker log for example 2:

WebUI: got an external command {'cmd_line': u'[1410960339] ACKNOWLEDGE_HOST_PROBLEM;server1.com;1;0;1;sebastien;trait\xe9 '}
rendered in 0.040030002594
88.125.125.65 - - [17/Sep/2014:15:25:39 +0200] "GET /action/ACKNOWLEDGE_HOST_PROBLEM/server1.com/1/0/1/sebastien/trait%C3%A9%20?callback=_jqjsp&_1410960374102= HTTP/1.1" 200 48 "http://shinken.com:7767/host/server1.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"
[1410960340] Debug :   [broker-master] Begin Loop: managing old broks (0)
[1410960340] Debug :   [broker-master] External Queue len (WebUI): 0
[1410960340] Debug :   [broker-master] External Queue len (Livestatus): 0
[1410960340] Debug :   [broker-master] External Queue len (NPCDMOD): 0
[1410960340] Debug :   [broker-master] 2 Broks get in 0.00746083259583
[1410960340] Debug :   [broker-master] 34 Broks get in 0.00412487983704
[1410960340] Debug :   [broker-master] 0 Broks get in 0.00226998329163
[1410960340] Debug :   [broker-master] 0 Broks get in 0.00556612014771
[1410960340] Debug :   [broker-master] 0 Broks get in 0.00276780128479
[1410960340] Debug :   [broker-master] Time to send 36 broks (0 secs)
[1410960340] Debug :   [broker-master] Enqueuing an external command '{'__module__': 'shinken.external_command', 'my_type': 'externalcommand', '__init__': <function __init__ at 0x1e686e0>, '__doc__': None}'
[1410960340] Debug :   [broker-master] Debug perf: ping [args:1.00135803223e-05] [aqu_lock:1.09672546387e-05] [calling:1.38282775879e-05] [json:2.59876251221e-05]
[1410960340] Debug :   [broker-master] Debug perf: push_broks [args:0.000290155410767] [aqu_lock:0.000291109085083] [calling:0.000311136245728] [json:0.00033712387085]
[1410960340] Debug :   [broker-master] Debug perf: ping [args:5.96046447754e-06] [aqu_lock:5.96046447754e-06] [calling:7.86781311035e-06] [json:1.38282775879e-05]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.0.3-py2.7.egg/shinken/webui/bottlecore.py", line 682, in _handle
    return callback(**args)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.0.3-py2.7.egg/shinken/webui/bottlecore.py", line 1333, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.0.3-py2.7.egg/shinken/http_daemon.py", line 363, in f_wrapper
    j = json.dumps(ret)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 195, in encode
    return encode_basestring_ascii(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 152: invalid continuation byte
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 210, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 268, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 195, in send_preamble
    self._write('Server: %s\r\n' % self.server_software)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 48827)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 640, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by naparuba** [comment]
I just saw that you seems to be without cherrypy3 lib, please give a try with it :)

**Comment by Caez83** [comment]
No change

ERROR: [broker-master] Unexpected error: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128) ; traceback: Traceback (most recent call last):
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 253, in run
    request_bytes = self.read_request()
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 160, in read_request
    request = self.get_request()
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 93, in get_request
    endline = buf.find('\n\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)

**Comment by naparuba** [comment]
Taht's not the same error, here it is located in the module

**Comment by Seb-Solon** [comment]
Fixed in livestatus module. Take the last tagged version

**Comment by Caez83** [comment]
It's OK with the last Github version of the module

Thank you very much
