### ISSUE TITLE
Poller crashed "unexepectedly"

### ISSUE THREAD

**Issue by DessaiImrane** [naparuba/shinken#1366]
Hi,

We noticed that the poller crashed when it get overloaded by checks 

For exemple, after a vCenter Crash, all check using "check_esx3.pl" are launched simultaneously causing a high CPU usage. ("check_esx3.pl is known for not being very efficient)

But, the poller crashed with this error : 

```
2014-11-06 00:26:49,971 [1415219209] Error :   Worker '1' exit with an unmanaged exception : Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 227, in work
    self.do_work(s, returns_queue, c)
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 273, in do_work
    self.manage_finished_checks()
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 194, in manage_finished_checks
    self.returns_queue.put(action)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.6/multiprocessing/managers.py", line 726, in _callmethod
    kind, result = conn.recv()
EOFError

```

This is not the first time. 

I'm ok if CPU is high and check are slow, but the poller should be running.

Any clue on that ?

**Comment by Seb-Solon** [comment]
No news, create a new ticket if necessary
