### ISSUE TITLE
Schedulerd crash

### ISSUE THREAD

**Issue by fullmetalucard** [naparuba/shinken#1433]
Hi,

I have just migrated a shinken 1.4 satellite to shinken 2.0.3 using the local install method (no access to internet from the machine).

As far as i can tell I allready successfully migrated the shinken master, but on this satellitte i get the following error when the shcedulerd is starting:

2015-01-05 12:25:15,199 [1420457115] Critical : I got an unrecoverable error. I have to exit
2015-01-05 12:25:15,200 [1420457115] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
2015-01-05 12:25:15,200 [1420457115] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.0.3-py2.6.egg/shinken/daemons/schedulerdaemon.py", line 479, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.0.3-py2.6.egg/shinken/daemon.py", line 322, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.0.3-py2.6.egg/shinken/daemons/schedulerdaemon.py", line 331, in do_loop_turn
    self.setup_new_conf()
  File "/usr/local/lib/python2.6/dist-packages/Shinken-2.0.3-py2.6.egg/shinken/daemons/schedulerdaemon.py", line 347, in setup_new_conf
    conf = cPickle.loads(conf_raw)
UnpicklingError: NEWOBJ class argument isn't a type object

Configuration: Debian Squeeze/Pyhton 2.6.6
I must precise that i've uninstalled the 1.4 version before installating the new one from the shinken-2.0.3.tar.gz package. 
Actually i d'on't know why i get this error..I allready merged my old configuration with new one of this version, and guess i've installed all the required packages.

No other errors on the other logfiles.

Any idea?

Regards,

**Comment by Seb-Solon** [comment]
Hi, all daemon must have the same version. Moreover i suggest you to use 2.2 instead of 2.0.3

**Comment by fullmetalucard** [comment]
Hi,

You're completely right, I installed shinken on my satellite via the tarball I got there: http://www.shinken-monitoring.org/download.php and thought there wasn't any 2.2 RC1 tarball. I finally installed the package available here:https://pypi.python.org/packages/source/S/Shinken/Shinken-2.2-RC1.tar.gz and finally make it work.

Thanks for your help. I close the issue.
