### ISSUE TITLE
[2.2-RC1] service template without host_name crashes arbiter

### ISSUE THREAD

**Issue by openglx** [naparuba/shinken#1438]
Doing a test with 2.2-RC1 with my current config from 2.0.3.

I have a service that looks like:

```
define service {
  register             0
  use                  service-interval-1min
  check_command        check_snmp_generic!$OID$!$WARN$!$CRIT$!2c!value
  service_description  bad-service
}
```

In 2.0.3 this service just doesn't do anything, as it never gets assigned to any host_name.

On 2.2-RC1 it is crashing the arbiter with the following backtrace:

```
[1420646244] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1420646244] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1420646244] CRITICAL: [Shinken] If you think this is a bug, create a new ticket including details mentioned in the README
[1420646244] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 590, in main
    self.load_config_file()
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 361, in load_config_file
    self.conf.create_objects(raw_objects)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/config.py", line 718, in create_objects
    self.create_objects_for_type(raw_objects, t)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/config.py", line 742, in create_objects_for_type
    setattr(self, prop, clss(lst, initial_index))
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/item.py", line 709, in __init__
    self.add_items(items, index_items)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/item.py", line 732, in add_items
    self.add_template(i)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/service.py", line 1062, in add_template
    "host_name%s" % (objcls, tpl.get_source())
AttributeError: 'Service' object has no attribute 'get_source'

```

I agree that the service is wrong, just think that the message could had been more helpful.

To identify which service was problematic I added the following snip to Items::add_items (/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/item.py line 728)

```
logger.debug("i %s get_name %s", i, i.get_name())
```

**Comment by david-guenault** [comment]
> In 2.0.3 this service just doesn't do anything, as it never gets assigned to any host_name.

No the service does nothing as it is just a template (register 0) unless another service inherit from this one. Please provide a full configuration set in order to be able to reproduce

**Comment by david-guenault** [comment]
sorry bad commit reference

**Comment by naparuba** [comment]
bug confirmed
