### ISSUE TITLE
[2.2-RC1] contact with single contactgroup crashes arbiter

### ISSUE THREAD

**Issue by openglx** [naparuba/shinken#1439]
Doing a test with 2.2-RC1 with my current config from 2.0.3.

I have a contact that looks like:

```
define contact {
         alias                          Jane Doe
         contact_name                   jdoe
         email                          jane.doe@example.com
        use                           contact-human
        contactgroups                 Team1
}

```

Whilst parsing this contact the arbiter crashes with this message:

```
[1420648092] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1420648092] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1420648092] CRITICAL: [Shinken] If you think this is a bug, create a new ticket including details mentioned in the README
[1420648092] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 590, in main
    self.load_config_file()
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 385, in load_config_file
    self.conf.explode()
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/config.py", line 1059, in explode
    self.contacts.explode(self.contactgroups, self.notificationways)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2_RC1-py2.6.egg/shinken/objects/contact.py", line 267, in explode
    for cg in c.contactgroups.split(','):
AttributeError: 'list' object has no attribute 'split'
```

**Comment by gst** [comment]
ok, got it:

we should have a 2.2-RC2, current master has a change/fix with contact.py file (exactly at the line it get that error).

temporarily you can replace the line:

```    for cg in c.contactgroups.split(','):```
by:
```    for cg in c.contactgroups:```

**Comment by openglx** [comment]
Same as #1425 then?

**Comment by gst** [comment]
that's the commit/change I talk about yes ;)

**Comment by Seb-Solon** [comment]
Can you try upstream version? I think I fixed it yeah.

**Comment by openglx** [comment]
Retested on 65ea078a7b8ae61fbbfca7951ba996963a5f3be8 - fixed.
Thanks
