### ISSUE TITLE
failed test_check_enter_downtime assert, but not on every execution

### ISSUE THREAD

**Issue by gst** [naparuba/shinken#1470]
NB: for who wants to hunt a not easily/always reproducible failed test assert..

I noticed it on Travis but the related logs are lost because I had re-executed travis run at that exact test/commit and travis don't keep the previous logs for a specific test/commit.

But I've copied it before ! (héééé Travis)

I tried reproducing it (by executing this test in a busy loop) but first attempts have failed.

```
...
test_special_macros_realm (test_macroresolver.TestMacroResolver) ... ok
test_check_defined_maintenance_period (test_maintenance_period.TestMaintPeriod) ... ok
test_check_enter_downtime (test_maintenance_period.TestMaintPeriod) ... FAIL

======================================================================
FAIL: test_check_enter_downtime (test_maintenance_period.TestMaintPeriod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/naparuba/shinken/test/test_maintenance_period.py", line 112, in test_check_enter_downtime
    self.assertEqual(1, len(self.sched.downtimes))
AssertionError: 1 != 0
```

**Comment by naparuba** [comment]
arg, another time care problem in the checks?

**Comment by gst** [comment]
seem like yep ;)

**Comment by gst** [comment]
reproduced by starting lot (200) of this test instance in parallel : 
```
$ rm -f failed; touch failed; n=$(jobs|wc -l) ; { for x in $(seq 200) ; do ( nosetests -xv test_maintenance_period:TestMaintPeriod.test_check_enter_downtime &> res_$x || { echo "===> $x failed ==="   >&4 ; } ) & done 4>&1 &>/dev/null ; while sleep 1 ; do echo ; test $(jobs|wc -l) -eq $n && break ; done ; } >failed  ; cat failed
```
output:  ===> 134 failed ===
```
$ head -10 res_134 
test_check_enter_downtime (test_maintenance_period.TestMaintPeriod) ... FAIL

======================================================================
FAIL: test_check_enter_downtime (test_maintenance_period.TestMaintPeriod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gstarck/work/work/SFL/Supervision/shinken/test/test_maintenance_period.py", line 112, in test_check_enter_downtime
    self.assertEqual(1, len(self.sched.downtimes))
AssertionError: 1 != 0
-------------------- >> begin captured stdout << ---------------------                                                                         
```

**Comment by gst** [comment]
unfortunately this trick to raise the system load to trigger this failed assert doesn't often succeed in this case.. or nearly never..  damn. which makes it more difficult to investigate / understand the race condition..
