### ISSUE TITLE
"shinken install" fails on TypeError: do_install() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1548]
```
# shinken install
Traceback (most recent call last):
  File "/usr/bin/shinken", line 479, in <module>
    CLI.one_loop(command_args)
  File "/usr/bin/shinken", line 277, in one_loop
    f(*cmd_args,**cmd_opts.__dict__)
TypeError: do_install() takes exactly 3 arguments (2 given)
```

would be nice to have a small help message. 

shinken deployed by jessie debian packages : 

```
ii  shinken                           2.0.3-4               all                   Flexible monitoring tool - Meta-package
```

Is there a 2.2 packaged for debian somewhere ?

**Comment by naparuba** [comment]
There is a bad mix between your shinken lib and the cli modules version
(/var/lib/shinken/cli). Please open the ticket on debian tickets :)

**Comment by arthurlogilab** [comment]
On a jessie, installing via pip install I get the same error

**Comment by Seb-Solon** [comment]
This is not related to packaging. I can reproduce this on the upstream version by doing : 

```
./shinken/bin/shinken_cli.py install 
Traceback (most recent call last):
  File "./shinken/bin/shinken_cli.py", line 541, in <module>
    main()
  File "./shinken/bin/shinken_cli.py", line 537, in main
    CLI.one_loop(command_args)
  File "./shinken/bin/shinken_cli.py", line 317, in one_loop
    f(*cmd_args, **cmd_opts.__dict__)
TypeError: do_install() takes exactly 3 arguments (2 given)
```
you can have help with
```
 ./shinken/bin/shinken_cli.py install --help
Options:
  --version        show program's version number and exit
  -h, --help       show this help message and exit
  --local          Use a local directory instead of the shinken.io version
  --download-only  Only download the package
```

Args parsing is hackish in shinken cli because it does not argparse that provide parsing for subcommands
