### ISSUE TITLE
Unknow method module import-glpi

### ISSUE THREAD

**Issue by algorys** [naparuba/shinken#1563]
Hello,

I'm trying to use the module import-glpi, and I have this error in log of arbiter : 
[1428486801] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 346, in load_config_file
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-glpi/module.py", line 149, in get_objects
    all_hostgroups = self.con.monitoring.shinkenHostgroups(arg)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'Unknown method (monitoring.shinkenHostgroups)'>

Is there a way to "patch" this ? Because I have search on web for this issue, but found nothing to resolve it.

Shinken 2.2 / GLPI 0.84.8

**Comment by mohierf** [comment]
1/ You should create an issue in the module repository : https://github.com/shinken-monitoring/mod-import-glpi

2/ Please post your configuration : Shinken configuration, Glpi WS configuration and shinken file import-glpi.cfg

**Comment by algorys** [comment]
I did it. Thanks

**Comment by mohierf** [comment]
This issue may be closed => @naparuba
