### ISSUE TITLE
[Shinken 2.2] 'NoneType' object has no attribute 'dfs_loop_status'

### ISSUE THREAD

**Issue by k0ste** [naparuba/shinken#1576]
If comment duplicate_foreach like this

```
define service {
use				service-nwc-link-state
host_name			host1
service_description		INTERFACE-$KEY$-STATE
duplicate_foreach		_iface
}
define service {
name				service-dependencies
register			0
service_dependencies		host1,INTERFACE-$KEY$-STATE
#duplicate_foreach		_iface
}
define service {
use				service-apcupsd-bcharge,service-dependencies
host_name			host1
service_description		APC-BATTERY-CHARGE
}
```

Got this:

```
[1429171524] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1429171524] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1429171524] CRITICAL: [Shinken] If you think this is a bug, create a new ticket including details mentioned in the README
[1429171524] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 594, in main
    self.load_config_file()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 452, in load_config_file
    self.confs = self.conf.cut_into_parts()
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1909, in cut_into_parts
    self.create_packs(nb_parts)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1702, in create_packs
    tmp_packs = g.get_accessibility_packs()
  File "/usr/lib/python2.7/site-packages/shinken/graph.py", line 125, in get_accessibility_packs
    node.dfs_loop_status = 'DFS_UNCHECKED'
AttributeError: 'NoneType' object has no attribute 'dfs_loop_status'

Traceback (most recent call last):
  File "/bin/shinken-arbiter", line 116, in <module>
    daemon.main()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 594, in main
    self.load_config_file()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 452, in load_config_file
    self.confs = self.conf.cut_into_parts()
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1909, in cut_into_parts
    self.create_packs(nb_parts)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1702, in create_packs
    tmp_packs = g.get_accessibility_packs()
  File "/usr/lib/python2.7/site-packages/shinken/graph.py", line 125, in get_accessibility_packs
    node.dfs_loop_status = 'DFS_UNCHECKED'
AttributeError: 'NoneType' object has no attribute 'dfs_loop_status'
```

**Comment by naparuba** [comment]
I give a test.


![show me](https://cloud.githubusercontent.com/assets/445325/7176698/df237da8-e420-11e4-9ada-9c5edf0c931f.gif)

**Comment by naparuba** [comment]
I cannot reproduce with tests (got [1429173067] ERROR: [Shinken] The service object 'INTERFACE-eth0-STATE'  is part of a circular parent/child chain! in my test).

Can you provide us a test case that fail? thanks :)

**Comment by k0ste** [comment]
Ooookay, full configs:

host definition:
```
define host {
use				generichost-gateway
host_name			novosiblenina.opentech.local
display_name			novosiblenina.opentech.local
address				192.168.5.1
alias				nsk-lenina1-novosiblenina
notes				Address

_NS				$HOSTADDRESS$
_NSHOSTNAME			$HOSTNAME$
_NSEXPECT			$HOSTADDRESS$
_NSWARNING			5
_NSCRITICAL			10

_LDAPSERVER			$HOSTADDRESS$
_LDAPBASE			$LDAPBASE$
_LDAPDN				$LDAPDN$
_LDAPPASSWORD			$LDAPPASSWORD$
_LDAPWARNING			5
_LDAPCRITICAL			10

_APCWAR				50
_APCCRIT			10

_SQUIDPORT			3129
_SQUIDURI			http://ya.ru/
_SQUIDEXPECT			200

#other possible values: udp/ipv4, udp6, udp/ipv6, tcp, tcp4, tcp/ipv4, tcp6, tcp/ipv6
_NWCDOMAIN			udp/ipv4
_NWCPROTO			2c
_SNMPCOMMUNITY			$SNMPCOMMUNITYREAD$
_NWCTIMEOUT			10
_NWCUNIT			%
_NWCIFACEWARNING		95
_NWCIFACECRITICAL		100

_iface				tap0$(10.9.0.82)$,tap1$(10.10.0.79)$
}
```

service definition:

```
define service {
use				service-nwc-link-state
host_name			novosiblenina.opentech.local
service_description		INTERFACE-$KEY$-STATE
duplicate_foreach		_iface
}
define service {
name				novosiblenina.opentech.local-dependencies
register			0
service_dependencies		novosiblenina.opentech.local,INTERFACE-$KEY$-STATE
duplicate_foreach		_iface
}
define service {
use				service-apcupsd-bcharge,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		APC-BATTERY-CHARGE
}
define service {
use				service-dns-resolver,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		DNS-RESOLVER
}
define service {
use				service-openldap-connection,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		OPENLDAP-CONNECTION
}
define service {
use				service-squid-connection,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		SQUID-CONNECTION
}
define service {
use				service-nfs-connection,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		NFS-CONNECTION
}
define service {
use				service-raid-mdstat,novosiblenina.opentech.local-dependencies
host_name			novosiblenina.opentech.local
service_description		MDRAID-STATUS
}
```

With this configs i receive:

```
[1429176960] INFO: [Shinken] Checking services...
[1429176960] WARNING: [Shinken] [service::APC-BATTERY-CHARGE] duplicate service name (u'novosiblenina.opentech.local', u'APC-BATTERY-CHARGE') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:13, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1429176960] WARNING: [Shinken] [service::DNS-RESOLVER] duplicate service name (u'novosiblenina.opentech.local', u'DNS-RESOLVER') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:18, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1429176960] WARNING: [Shinken] [service::OPENLDAP-CONNECTION] duplicate service name (u'novosiblenina.opentech.local', u'OPENLDAP-CONNECTION') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:23, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1429176960] WARNING: [Shinken] [service::SQUID-CONNECTION] duplicate service name (u'novosiblenina.opentech.local', u'SQUID-CONNECTION') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:28, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1429176960] WARNING: [Shinken] [service::NFS-CONNECTION] duplicate service name (u'novosiblenina.opentech.local', u'NFS-CONNECTION') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:33, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1429176960] WARNING: [Shinken] [service::MDRAID-STATUS] duplicate service name (u'novosiblenina.opentech.local', u'MDRAID-STATUS') in /etc/shinken/services/gateway/Novosibirsk/nsk-lenina1-novosiblenina.cfg:38, using lastly defined. You may manually set the definition_order parameter to avoid this message.
```
![selection_004](https://cloud.githubusercontent.com/assets/7759548/7178465/7994f322-e448-11e4-8cc1-1f1d2ac49881.jpg)
I think this bug to... or not?

For reproduce error comment duplicate_foreach on 2nd section of service definition.

**Comment by naparuba** [comment]
cannot reproduce, your conf is incomplete and when I fix it still invalid. Can you create a full test that fail in the /test and launch us a pull request? Thanks :)

**Comment by k0ste** [comment]
https://github.com/naparuba/shinken/pull/1577
