### ISSUE TITLE
Shinken-discovery - Python error

### ISSUE THREAD

**Issue by gramimoss** [naparuba/shinken#1584]
Hi I installed a fresh version on shinken 2.4-RC1 using the pip install method

When i try to run the shinken-discovery I get the following errors
```
shinken-discovery -c /etc/shinken/discovery/discovery.cfg -o /etc/shinken/hosts/discovery/ -r nmap -m 

--> pfkdbnfw01 isup 1
--> pfkdbnfw01 os linux
--> pfkdbnfw01 osversion 2.4.x
--> pfkdbnfw01 ostype wap
--> pfkdbnfw01 osvendor linux
--> pfkdbnfw01 macvendor usc information sciences inst
--> pfkdbnfw01 openports 22,53,80,1723,8291,53
--> pfkdbnfw01 fqdn pfkdbnfw01.pfksa.co.za
--> pfkdbnfw01 ip XXX.XXX.XXX.XXX 
Try to match windows linux
Try to match 2000 2.4.x
Try to match 2003 2.4.x
Try to match vista 2.4.x
Try to match 7 2.4.x
Try to match ^5036$ 22
Try to match ^5036$ 53
Try to match ^5036$ 80
Try to match ^5036$ 1723
Try to match switch wap
Try to match router wap
Try to match linux linux
Generating pfkdbnfw01 {u'+use': u'linux-snmp'}
Try to match 1 1
Generating pfkdbnfw01 {u'+use': u'generic-host'}
New prop use
Add linux-snmp
Already got linux-snmp add generic-host
Traceback (most recent call last):
  File "/usr/bin/shinken-discovery", line 170, in <module>
    d.match_rules()
  File "/usr/lib/python2.6/site-packages/shinken/discovery/discoverymanager.py", line 503, in match_rules
    dh.update_properties()
  File "/usr/lib/python2.6/site-packages/shinken/discovery/discoverymanager.py", line 161, in update_properties
    if isinstance(d[k], 'list'):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

I'm no programmer and hope that it is a quick fix.

**Comment by naparuba** [comment]
Fixed by: a02c8aae7f434d5c3455d59752fcb426f63b759e

If not reopen :)
