### ISSUE TITLE
Scheduler crash on a sub-realm...

### ISSUE THREAD

**Issue by 4l3c** [naparuba/shinken#1585]
Hi,
first of all, sorry if mistakes, I usualy speak french.

I actually test, shinken with realms configuration... 
Created hosts, hostgroups, services, realms,... installed shinken services on multiple vm's (only 1 arbiter on the main realm) (Vm with virtualbox, debian wheezy, full updated, no desktop environement)
But I have this problem, on my sub-realm, the scheduler service fail to load, when I check the logs the error is:
CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 532, in ma
in
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 342, in do
_loop_turn
    self.setup_new_conf()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 422, in se
tup_new_conf
    if p['use_ssl']:
UnboundLocalError: local variable 'p' referenced before assignment

Is it a bug? or I fail somewhere?

Thank you
Al3c

**Comment by naparuba** [comment]
Seems to be a bad mix between shinken versions.

**Comment by thiell** [comment]
Hi, I am testing Shinken these days with realms and got the same problem. I changed the line `if p['use_ssl']:` to `reac['use_ssl']:` in `shinken/daemons/schedulerdaemon.py` at line 422 (it looks like a wrong copy/paste from the pollers creation code block just above). Seems to work much better for me.
