### ISSUE TITLE
Bug in arbiter in version 2.4RC4

### ISSUE THREAD

**Issue by ddurieux** [naparuba/shinken#1595]
when run arbiter:

```
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 56 commands to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 20 hosts to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 9 hosts groups to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 6 services templates to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 180 services to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 3 timeperiods to Arbiter
[1429922479] WARNING: [Shinken] [GLPI Arbiter] Sending 5 contacts to Arbiter
[1429922479] INFO: [Shinken] [GLPI Arbiter] Sending all data to Arbiter
[1429922479] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1429922479] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1429922479] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1429922479] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 595, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 389, in load_config_file
    self.conf.linkify_templates()
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/objects/config.py", line 1845, in linkify_templates
    self.hosts.linkify_templates()
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/objects/item.py", line 1018, in linkify_templates
    self.linkify_item_templates(i)
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/objects/item.py", line 1000, in linkify_item_templates
    item.imported_from))
AttributeError: imported_from
```

**Comment by naparuba** [comment]
Please try with this:


diff --git a/shinken/daemons/arbiterdaemon.py b/shinken/daemons/arbiterdaemon.py
index 95b9a43..34f41ec 100644
--- a/shinken/daemons/arbiterdaemon.py
+++ b/shinken/daemons/arbiterdaemon.py
@@ -361,6 +361,10 @@ class Arbiter(Daemon):
                             # test if raw_objects[k] are already set - if not, add empty array
                             if k not in raw_objects:
                                 raw_objects[k] = []
+                            # put the imported_from property if the module is not already setting
+                            # it so we know where does this object came from
+                            if 'imported_from' not in x:
+                                x['imported_from'] = 'module:%s' % inst.get_name()
                             # now append the object
                             raw_objects[k].append(x)
                         logger.debug("Added %i objects to %s from module %s",



it basically only add the imported_from property in module objects is not set by the module (optionnal). thanks :)
