### ISSUE TITLE
Issue on poller spare on version 2.2

### ISSUE THREAD

**Issue by floppy84** [naparuba/shinken#1596]
Hi all,

i got an issue when i am connect my poller spare to shinken.

when i go to my spare host with spare module.
I run all module in debug mode with shinken -d start

On shinken spare host i can see this : 

[1430129746] DEBUG: [Shinken] HTTP: calling lock for push_actions
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/webui/bottlecore.py", line 682, in _handle
    return callback(**args)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/webui/bottlecore.py", line 1333, in wrapper
    rv = callback(_a, *_ka)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/http_daemon.py", line 362, in f_wrapper
    ret = f(**d)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/satellite.py", line 168, in push_actions
    self.app.add_actions(actions, int(sched_id))
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/satellite.py", line 663, in add_actions
    if a.id in self.schedulers[sched_id]['actions']:
KeyError: 2

On shinken host i got flapping issue like : 

INFO: [Shinken] Connection OK to the poller poller-spare
[1430129474] WARNING: [Shinken] Connection problem to the <type 'type'> poller-spare: Connexion error to http://cav-mgt-shinken-2:7771/ : The requested URL returned error: 500 Internal Server Error

I notify this to Naparuba, and he say me that is a bug.

**Comment by naparuba** [comment]
Is it still occuring with 2.4.3? Thanks.
