### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by algorys** [naparuba/shinken#1629]
Hello, I have a problem with the module ws-arbiter, he restart indefinitely...

[1431512095] INFO: [Shinken] I'm stopping module u'ws-arbiter' (pid=15138)
[1431512095] INFO: [Shinken] Starting external process for instance ws-arbiter
[1431512095] INFO: [Shinken] ws-arbiter is now started ; pid=15145
[1431512095] INFO: [Shinken] [ws-arbiter[15145]]: Now running..
[1431512095] INFO: [Shinken] [WS_Arbiter] Starting WS arbiter http socket
[1431512095] ERROR: [Shinken] [WS_Arbiter] Exception : [Errno 98] Address already in use
[1431512095] ERROR: [Shinken] [ws-arbiter] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/ws-arbiter/module.py", line 394, in main
    self.init_http()
  File "/var/lib/shinken/modules/ws-arbiter/module.py", line 369, in init_http
    self.srv = run(host=self.host, port=self.port, server='wsgirefselect')
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 2260, in run
    res = server.run(app)
  File "/usr/local/lib/python2.7/dist-packages/shinken/webui/bottlewebui.py", line 1971, in run
    srv = make_server(self.host, self.port, handler, **self.options)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 144, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

How can I solve this issue please ? Because I don't understand why he do that.

Thanks in advance.

**Comment by mohierf** [comment]
Obviously the port you configured for the arbiter Web Service module is already in use on your system.

Default configuration is to listen on 0.0.0.0:7760. Try to change this configuration in ws_arbiter.cfg file and to restart your Shinken

**Comment by algorys** [comment]
I have reboot my system and now I have the following issue : 

Restarting scheduler
[FAIL] FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/schedulerd.pid' (full output is in /tmp/bad_start_for_scheduler) ... failed!
 failed!
Restarting poller
[FAIL] FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/pollerd.pid' (full output is in /tmp/bad_start_for_poller) ... failed!
 failed!
Restarting reactionner
[....] FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/reactionnerd.pid' (full output is in /tmp/bad_start_for_reactionner)[FAI failed!
 failed!
Restarting broker
[FAIL] FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/brokerd.pid' (full output is in /tmp/bad_start_for_broker) ... failed!
 failed!
Restarting receiver
[FAIL] FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/receiverd.pid' (full output is in /tmp/bad_start_for_receiver) ... failed!
 failed!
Restarting arbiter
Doing config check
. ok
. ok

It do that each time I reboot. I have to reinstall shinken each time ?

**Comment by mohierf** [comment]
No, you do not have to reinstall. 

I had (and always have ...) this problem on a Debian virtual host. See #1624

**Comment by algorys** [comment]
OK... I solved with chmo 777... that's strange, because in 2.2 it does not that :)

**Comment by mohierf** [comment]
Take care that after restarting my server I still had the problem ... it seems that the `/var/run/shinken` directory is deleted and recreated after reboot !

**Comment by algorys** [comment]
Ok. That's why after each reboot there is need to do that...

Hmm do you have the same problem like me on your debian ?
https://github.com/ddurieux/glpi_monitoring/issues/170

I don't know if link to this....

**Comment by mohierf** [comment]
1/ After each reboot of my Debian on a VM, only the arbiter is running ! And I am obliged to stop, chmod, restart for each daemons to run properly

 2/ I am currently testing a fresh install of shinken 2.4, Glpi 0.85, Monitoring 0.85 ... I will keep you informed about my results concerninh Shinken restart order from Glpi :-)
