### ISSUE TITLE
Scheduler crash with attributeError on reactionner_tag 

### ISSUE THREAD

**Issue by oliiivier** [naparuba/shinken#1640]
With the shinken 2.4, my scheduler crash with this error message : 
1431691877] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1431691877] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1431691877] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1431691877] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/shinken/daemons/schedulerdaemon.py", line 532, in main
    self.do_mainloop()
  File "/usr/lib/python2.6/site-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/lib/python2.6/site-packages/shinken/daemons/schedulerdaemon.py", line 344, in do_loop_turn
    self.sched.run()
  File "/usr/lib/python2.6/site-packages/shinken/scheduler.py", line 1679, in run
    f()
  File "/usr/lib/python2.6/site-packages/shinken/scheduler.py", line 573, in scatter_master_notifications
    childnotifications = item.scatter_notification(a)
  File "/usr/lib/python2.6/site-packages/shinken/objects/schedulingitem.py", line 1329, in scatter_notification
    rt = cmd.reactionner_tag
AttributeError: reactionner_tag

In schedulingitem.py, I have modified the scatter_notification to workaround : 
    def scatter_notification(self, n):
	[...]
            for cmd in notif_commands:
                #rt = cmd.reactionner_tag
                #mt = cmd.module_type
                #ee = cmd.cmd.enable_environment_macros
                rt = 'None'
                mt = 'None'
                ee = False
                child_n = Notification(n.type, 'scheduled', 'VOID', cmd, self,
                                       contact, n.t_to_go, escalated=escalated,
                                       timeout=cls.notification_timeout,
                                       notif_nb=n.notif_nb, reactionner_tag=rt,
                                       module_type=mt,
                                       enable_environment_macros=ee)

 

detail of my configuation : 
- 1 scheduler
- 1 reactionner
- 1 notificationway : email

define notificationway{
       notificationway_name            email
       service_notification_period     24x7
       host_notification_period        24x7
       service_notification_options    c,w,r
       host_notification_options       d,u,r,f,s
       service_notification_commands   notify-service-by-email ; send service notifications via email
       host_notification_commands      notify-host-by-email    ; send host notifications via email
}

## Notify Host by Email
define command {
    command_name    notify-host-by-email
    command_line    /usr/bin/printf "%b" "Shinken Notification\n\nType:$NOTIFICATIONTYPE$\nHost: $HOSTNAME$\nState: $HOSTSTATE$\nAddress: $HOSTADDRESS$\nInfo: $HOSTOUTPUT$\nDate/Time: $DATE$ $TIME$\n" | /usr/bin/mail -s "Host $HOSTSTATE$ alert for $HOSTNAME$" $CONTACTEMAIL$
        reactionner_tag  None
}

## Notify Service by Email
define command {
    command_name    notify-service-by-email
    command_line    /usr/bin/printf "%b" "Shinken Notification\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTNAME$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $DATE$ $TIME$\nAdditional Info : $SERVICEOUTPUT$\n" | /usr/bin/mail -s "** $NOTIFICATIONTYPE$ alert - $HOSTNAME$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$
        reactionner_tag None
}

define reactionner {
    reactionner_name    reactionner-master
    address            localhost   
    port                7769
    spare               0

    ## Optionnal
    manage_sub_realms   0   ; Does it take jobs from schedulers of sub-Realms?
    min_workers         1   ; Starts with N processes (0 = 1 per CPU)
    max_workers         15  ; No more than N processes (0 = 1 per CPU)
    polling_interval    1   ; Get jobs from schedulers each 1 second
    timeout             3   ; Ping timeout
    data_timeout        120 ; Data send timeout
    max_check_attempts  3   ; If ping fails N or more, then the node is dead
    check_interval      60  ; Ping node every N seconds

    ## Modules
    modules

    # Reactionner tags are the tag that the reactionner will manage. Use None as tag name to manage
    # untaggued notification/event handlers
    #reactionner_tags     email

    # Enable https or not
    use_ssl               0
    # enable certificate/hostname check, will avoid man in the middle attacks
    hard_ssl_name_check   0

    ## Advanced
    realm   All
}

define scheduler {
    scheduler_name      scheduler-master ; Just the name
    address             localhost   ; IP or DNS address of the daemon
    port                7768        ; TCP port of the daemon
    ## Optional
    spare               0   ; 1 = is a spare, 0 = is not a spare
    weight              1   ; Some schedulers can manage more hosts than others
    timeout             3   ; Ping timeout
    data_timeout        120 ; Data send timeout
    max_check_attempts  3   ; If ping fails N or more, then the node is dead
    check_interval      60  ; Ping node every N seconds

    ## Interesting modules that can be used:
    # - pickle-retention-file     = Save data before exiting in flat-file
    # - mem-cache-retention   = Same, but in a MemCache server
    # - redis-retention      = Same, but in a Redis server
    # - retention-mongodb    = Same, but in a MongoDB server
    # - nagios-retention     = Read retention info from a Nagios retention file
    #                         (does not save, only read)
    # - snmp-booster             = Snmp bulk polling module
    modules pickle-retention-file

    ## Advanced Features
    # Realm is for multi-datacenters
    realm   All

    # Skip initial broks creation. Boot fast, but some broker modules won't
    # work with it! (like livestatus for example)
    skip_initial_broks  0

    # In NATted environments, you declare each satellite ip[:port] as seen by
    # *this* scheduler (if port not set, the port declared by satellite itself
    # is used)
    #satellitemap    poller-1=1.2.3.4:7771, reactionner-1=1.2.3.5:7769, ...

    # Enable https or not
    use_ssl               0
    # enable certificate/hostname check, will avoid man in the middle attacks
    hard_ssl_name_check   0
}

thanks for help,

best regards, 
olivier

**Comment by oliiivier** [comment]
my workaround works with the scheduler, I see Notification message, but the reactionner dont receive any command to execute to send some email. So, I have 2 choice : 
- work with the original source and have the scheduler crash in first 5 minutes....
- work with my lasy workaround and have no notification execution... 

have you any idea on my problem??
thanks, 
olivier

**Comment by oliiivier** [comment]
I found the solution for my problem : 
    def scatter_notification(self, n):
        cls = self.__class__
        childnotifications = []
        escalated = False
        if n.contact:
            # only master notifications can be split up
            return []
        if n.type == 'RECOVERY':
            if self.first_notification_delay != 0 and len(self.notified_contacts) == 0:
                # Recovered during first_notification_delay. No notifications
                # have been sent yet, so we keep quiet
                contacts = []
            else:
                # The old way. Only send recover notifications to those contacts
                # who also got problem notifications
                contacts = list(self.notified_contacts)
            self.notified_contacts.clear()
        else:
            # Check is an escalation match. If yes, get all contacts from escalations
            if self.is_escalable(n):
                contacts = self.get_escalable_contacts(n)
                escalated = True
            # else take normal contacts
            else:
                contacts = self.contacts

        for contact in contacts:
            # We do not want to notify again a contact with
            # notification interval == 0 that has been already
            # notified. Can happen when a service exit a dowtime
            # and still in crit/warn (and not ack)
            if n.type == "PROBLEM" and \
                    self.notification_interval == 0 \
                    and contact in self.notified_contacts:
                continue
            # Get the property name for notif commands, like
            # service_notification_commands for service
            notif_commands = contact.get_notification_commands(cls.my_type)
            #naglog_result('info', '-- cls.my_type : %s' % (cls.my_type))
            #naglog_result('info', '-- contact.contact_name : %s' % (contact.contact_name))
            #naglog_result('info', '-- notif_commands : %s' % (vars(notif_commands)))
            #naglog_result('info', '-- notif_commands : %s' % (notif_commands.service_notification_commands)

            for cmd in notif_commands:
                try:
                    # solution is here in next 3 lines :
                    rt = getattr(cmd,'reactionner_tag','None')
                    mt = getattr(cmd,'module_type','None')
                    ee = getattr(cmd,'enable_environment_macros',False)
                    child_n = Notification(n.type, 'scheduled', 'VOID', cmd, self,
                                           contact, n.t_to_go, escalated=escalated,
                                           timeout=cls.notification_timeout,
                                           notif_nb=n.notif_nb, reactionner_tag=rt,
                                           module_type=mt,
                                           enable_environment_macros=ee)
                    if not self.notification_is_blocked_by_contact(child_n, contact):
                        # Update the notification with fresh status information
                        # of the item. Example: during the notification_delay
                        # the status of a service may have changed from WARNING to CRITICAL
                        self.update_notification_command(child_n)
                        self.raise_notification_log_entry(child_n)
                        self.notifications_in_progress[child_n.id] = child_n
                        childnotifications.append(child_n)

                        if n.type == 'PROBLEM':
                            # Remember the contacts. We might need them later in the
                            # recovery code some lines above
                            self.notified_contacts.add(contact)
                except AttributeError:
                    naglog_result('info', '-- AttributeError : %s' % (dir(cmd)))
                    naglog_result('info', '-- AttributeError : %s' % (vars(cmd)))
                    naglog_result('info', '-- cmd.get_name : %s' % (cmd.get_name()))
                    naglog_result('info', '-- cmd.get_command_and_args : %s' % (cmd.get_command_and_args()))
                    naglog_result('info', '-- cmd.command : %s' % (cmd.command))
                    naglog_result('info', '-- cmd.reactionner_tag : %s' % (getattr(cmd,'reactionner_tag','pas trouve')))
                    pass

        return childnotifications
