### ISSUE TITLE
Scheduler crash when missing attributes in NotificationsWay

### ISSUE THREAD

**Issue by Corbyn** [naparuba/shinken#1673]
Hi,
I have a problem with our Shinken 2.4:
I accidentally missed the 'service_notification_commands' and 'host_notification_commands' attributes when defining an new NotificationWay.
After some time the scheduler crashed with the following message:

    [1436371757] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
    [1436371757] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
    [1436371757] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
    [1436371757] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
      File "/opt/apps/shinken/shinken/daemons/schedulerdaemon.py", line 532, in main
        self.do_mainloop()
      File "/opt/apps/shinken/shinken/daemon.py", line 333, in do_mainloop
        self.do_loop_turn()
      File "/opt/apps/shinken/shinken/daemons/schedulerdaemon.py", line 344, in do_loop_turn
        self.sched.run()
      File "/opt/apps/shinken/shinken/scheduler.py", line 1679, in run
        f()
      File "/opt/apps/shinken/shinken/scheduler.py", line 573, in scatter_master_notifications
        childnotifications = item.scatter_notification(a)
      File "/opt/apps/shinken/shinken/objects/schedulingitem.py", line 1326, in scatter_notification
        notif_commands = contact.get_notification_commands(cls.my_type)
      File "/opt/apps/shinken/shinken/objects/contact.py", line 167, in get_notification_commands
        r.extend(getattr(nw, notif_commands_prop))
    AttributeError: 'NotificationWay' object has no attribute 'service_notification_commands'

Ok, these attributes are mandatory, but the actual problem is that the Shinken config check did not recognize the missing attributes and stated everything was ok...

**Comment by naparuba** [comment]
Thanks, we will solve this.
