### ISSUE TITLE
Shinken not accessible

### ISSUE THREAD

**Issue by halysan** [naparuba/shinken#1692]
Hi !

Every night my Shinken stops working without reason..
I have a Debian Jessie and Shinken 2.2

My log reactionnerd.log:

<code>
2015-08-06 10:48:14,186 [1438850894] Warning : Printing stored debug messages prior to our daemonization
2015-08-06 13:17:21,801 [1438859841] Error :   manage_returns exception:: <class 
2015-08-06 22:16:31,887 [1438892190] Error :   manage_returns exception:: <class 'shinken.http_client.HTTPException'>,Connexion error to http://localhost:7768/ : Operation timed out after 3005 milliseconds with 0 bytes received
2015-08-06 22:16:39,167 [1438892199] Warning : [reactionner] Scheduler scheduler is not initialized or has network problem: Connexion error to http://localhost:7768/ : Connection time-out
...
2015-08-06 22:16:44,188 [1438892204] Warning : [reactionner] Scheduler scheduler is not initialized or has network problem: Connexion error to http://localhost:7768/ : Failed to connect to localhost port 7768: Connection refused
...
2015-08-06 22:16:45,210 [1438892205] Warning : [reactionner] Scheduler scheduler is not initialized or has network problem: Connexion error to http://localhost:7768/ : Failed to connect to localhost port 7768: Connection refused
2015-08-06 22:16:45,210 [1438892205] Warning : Sent failed!
</code>

My log brokerd this morning:
<code>
2015-08-07 09:05:28,837 [1438931128] Warning : Printing stored debug messages prior to our daemonization
2015-08-07 09:05:34,937 [1438931134] Error :   [broker] [Graphite broker] Graphite Carbon instance network socket! IOError:[Errno 111] Connection refused
2015-08-07 09:05:34,938 [1438931134] Error :   [broker] The instance graphite raised an exception [Errno 111] Connection refused, I remove it!
2015-08-07 09:05:34,956 [1438931134] Error :   [broker] Back trace of this remove: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/shinken/modulesmanager.py", line 158, in try_instance_init
    inst.init()
  File "/usr/share/pyshared/shinken/modules/graphite/module.py", line 90, in init
    self.con.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
2015-08-07 09:05:34,956 [1438931134] Warning : [broker] The module 'graphite' failed to init, I will try to restart it later
2015-08-07 09:06:57,060 [1438931217] Warning : Printing stored debug messages prior to our daemonization
</code>

Every morning my interface Thruk is not accessible...
Log:
<code>
2015/08/03 10:27:38][shinken][INFO][Thruk] [thrukadmin][Shinken] cmd: COMMAND [1438590458] SCHEDULE_SVC_CHECK;r1-lt1-1;Interface GigabitEthernet;1438590458
[2015/08/06 09:09:23][shinken][ERROR][Thruk] No Backend available
[2015/08/06 09:09:23][shinken][ERROR][Thruk] on page: http://IP-SRV/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail
[2015/08/06 09:09:23][shinken][ERROR][Thruk] Shinken: ERROR: failed to connect - Connection refused. (127.0.0.1:50000)
[2015/08/06 09:09:26][shinken][ERROR][Thruk] No Backend available
[2015/08/06 09:09:26][shinken][ERROR][Thruk] on page: http://IP-SRV/thruk/cgi-bin/status.cgi?host=all
[2015/08/06 09:09:26][shinken][ERROR][Thruk] Shinken: ERROR: failed to connect - Connection refused. (127.0.0.1:50000)
[2015/08/06 09:09:27][shinken][ERROR][Thruk] No Backend available
[2015/08/06 09:09:27][shinken][ERROR][Thruk] on page: http://IP-SRV/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail
[2015/08/06 09:09:27][shinken][ERROR][Thruk] Shinken: ERROR: failed to connect - Connection refused. (127.0.0.1:50000)
[2015/08/06 09:09:31][shinken][ERROR][Thruk] No Backend available
[2015/08/06 09:09:31][shinken][ERROR][Thruk] on page: http://IP-SRV/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail
[2015/08/06 09:09:31][shinken][ERROR][Thruk] Shinken: ERROR: failed to connect - Connection refused. (127.0.0.1:50000)
[2015/08/06 09:09:33][shinken][ERROR][Thruk] No Backend available
[2015/08/06 09:09:33][shinken][ERROR][Thruk] on page: http://IP-SRV/thruk/cgi-bin/statusmap.cgi?host=all
[2015/08/06 09:09:33][shinken][ERROR][Thruk] Shinken: ERROR: failed to connect - Connection refused. (127.0.0.1:50000)
[2015/08/06 17:21:32][shinken][INFO][Thruk] [thrukadmin][Shinken] cmd: COMMAND [1438874492] SCHEDULE_HOST_CHECK;breka.assistance;1438874492
</code>

If I restart shinken/apache2/thruk always not accessible.
But if retart the computer, the interface Web-UI and Thruk are available.

Every day always the same story..

Can you have an idea?
Best regards,

**Comment by leoluk** [comment]
May be related to https://github.com/naparuba/shinken/issues/1659

**Comment by naparuba** [comment]
Is it still the case with 2.4.3? Thanks.
