### ISSUE TITLE
[Shinken] Back trace of the error: Traceback (most recent call last)

### ISSUE THREAD

**Issue by Sismic** [naparuba/shinken#1716]
when i send a restart commad to service shinken, arbiter can't start

[1441697392] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 606, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 344, in load_config_file
    self.conf.create_objects(raw_objects)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/config.py", line 1083, in create_objects
    self.create_objects_for_type(raw_objects, t)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/config.py", line 1102, in create_objects_for_type
    o = cls(obj_cfg)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/item.py", line 100, in __init__
    val = self.properties[key].pythonize(params[key])
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/property.py", line 169, in pythonize
    val = unique_value(val).lower()
AttributeError: 'int' object has no attribute 'lower'
 
Traceback (most recent call last):
  File "/usr/bin/shinken-arbiter", line 130, in <module>
    main()
  File "/usr/bin/shinken-arbiter", line 122, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 606, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 344, in load_config_file
    self.conf.create_objects(raw_objects)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/config.py", line 1083, in create_objects
    self.create_objects_for_type(raw_objects, t)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/config.py", line 1102, in create_objects_for_type
    o = cls(obj_cfg)
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/objects/item.py", line 100, in __init__
    val = self.properties[key].pythonize(params[key])
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4-py2.7.egg/shinken/property.py", line 169, in pythonize
    val = unique_value(val).lower()
AttributeError: 'int' object has no attribute 'lower'

**Comment by jbnitro** [comment]
Hello 
I have the same problem
How did you solve your problem?

**Comment by naparuba** [comment]
Seems that one of your property have the wrong type. We will catch and try the error
