### ISSUE TITLE
error when launch poller. Erreur qui est arrivée du jour au lendemain | system Up depuis 1 an

### ISSUE THREAD

**Issue by Jm0u** [naparuba/shinken#1719]
[1443167321] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/local/shinken/shinken/satellite.py", line 936, in main
    self.do_daemon_init_and_start()
  File "/usr/local/shinken/shinken/daemon.py", line 477, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/shinken/shinken/daemon.py", line 356, in check_parallel_run
    os.kill(pid, 0)
OSError: [Errno 1] Operation not permitted

Traceback (most recent call last):
  File "/usr/local/shinken/bin/shinken-poller", line 80, in <module>
    daemon.main()
  File "/usr/local/shinken/shinken/satellite.py", line 936, in main
    self.do_daemon_init_and_start()
  File "/usr/local/shinken/shinken/daemon.py", line 477, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/shinken/shinken/daemon.py", line 356, in check_parallel_run
    os.kill(pid, 0)
OSError: [Errno 1] Operation not permitted

**Comment by geektophe** [comment]
Could you give us more context ?

- Which os/distribution are you using ?
- When does this error occur ? Is it only when you try to start the poller, or does it happen while it runs ?
- Do you manage to start the service ?
- How many pollers do you have ? Are there other running correctly ?
- Are you sure nothing happened on the server that could explain this problem ?

**Comment by gst** [comment]
> File "/usr/local/shinken/shinken/daemon.py", line 356, in check_parallel_run
> os.kill(pid, 0)
> OSError: [Errno 1] Operation not permitted

normally this can only be caused by a "stalled" pid file : it contains a pid which is not anymore a poller process. 
Actually given the error we can also say that the pid correspond to a process owned by another user than the one running shinken.
This can happen if the poller previously died/exited in a hard way (kill -9) and after that the pid stored in the pid file was reused by another process on the system, then the poller tried to start but encouter the error trying to "check" the process referenced by the pidfile.
Solution: delete the pid file.

**Comment by geektophe** [comment]
Any update, did it solve your issue ?
