### ISSUE TITLE
Configuration fails

### ISSUE THREAD

**Issue by sblancov** [naparuba/shinken#1725]
I have looked for any issue related to this problem but I have not found anything. So, I think I have found a bug.

Do not ask why, I had a config file like this one:
```
define host {
    use                         generic-bp-host
    check_command               bp_rule!
(onehost | anotherhost)
    notifications_enabled       1
    alias                       bp_hello
    host_name                   BP_HELLO
    business_impact             1
}
```
**That config file has a new line where it should not** (after bp_rule!).
So, when I executed this command:
```
/usr/bin/shinken-arbiter -v -c /etc/shinken/shinken.cfg
```
I got this trace from arbiter:
```
(->) Fetching new object definitions:
	1	contact(s)
	460	host(s)
	1	hostbusinessprocess(s)
	1	notificationway(s)
(->) Looking for errors:
Traceback (most recent call last):
  File "/usr/bin/shinken-arbiter", line 116, in <module>
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 594, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 430, in load_config_file
    self.conf.create_business_rules_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1285, in create_business_rules_dependencies
    self.hosts.create_business_rules_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/host.py", line 1274, in create_business_rules_dependencies
    h.create_business_rules_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/schedulingitem.py", line 1645, in create_business_rules_dependencies
    elts = self.business_rule.list_all_elements()
AttributeError: 'NoneType' object has no attribute 'list_all_elements'
```
and it drove me crazy because I did not write the config file.

Anyway, I think you do not want to print any Traceback. It probably better check weather the config file is right or not, and print a beautiful and a descriptive error as in other cases.

**Comment by geektophe** [comment]
I think the error may be related to the newline after the `bp_rule` directive without `\` (backslash) nor white space before the business rule expression. This may mislead the configuration parser, letting him think that the business rule is empty.

Could you try to write it on a single line (`bp_rule!(onehost | anotherhost)`) and have a test ?

**Comment by sblancov** [comment]
bp_rule!(onehost | anotherhost) works. It must. It does. That is not the problem.

The file is incorrect as I have detailed in my previous message. So I think Shinken should check the correctness of configuration files, and then, print an error instead of throw and exception that stops its execution.

Shinken show errors about configuration files, but not in this case.

**Comment by geektophe** [comment]
Sorry for my late answer. I'll check if we can improve that.

**Comment by naparuba** [comment]
We should block elements parameter that are not known, unless for very specific case (like timeperiods or modules).
