### ISSUE TITLE
ConfigCheck failed: AttributeError: 'Discoveryrule' object has no attribute 'configuration_warnings'

### ISSUE THREAD

**Issue by mfsny** [naparuba/shinken#1765]
Staring the service fails:
````
$ service shinken restart
Restarting scheduler
Restarting poller                                          [  OK  ]
Restarting reactionner                                     [  OK  ]
Restarting broker                                          [  OK  ]
Restarting receiver                                        [  OK  ]
Restarting arbiter                                         [  OK  ]
Doing config check [FAILED]
full result is in /tmp/shinken_checkconfig_result          [WARNING]
ConfigCheck failed: AttributeError: 'Discoveryrule' object has no attribute 'configuration_warnings'
````
/tmp/shinken_checkconfig_result:
````
[1448471165] INFO: [Shinken] My own modules:
[1448471165] INFO: [Shinken] Modules directory: /var/lib/shinken/modules
[1448471165] INFO: [Shinken] Modules directory: /var/lib/shinken/modules
[1448471165] INFO: [Shinken] I correctly loaded the modules: []
[1448471165] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1448471165] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1448471165] CRITICAL: [Shinken] If you think this is a bug, create a new ticket including details mentioned in the README
[1448471165] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 594, in main
    self.load_config_file()
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 365, in load_config_file
    self.conf.create_objects(raw_objects)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/config.py", line 717, in create_objects
    self.create_objects_for_type(raw_objects, t)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/config.py", line 741, in create_objects_for_type
    setattr(self, prop, clss(lst, initial_index))
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/item.py", line 721, in __init__
    self.add_items(items, index_items)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/item.py", line 743, in add_items
    self.add_item(i, index_items)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/item.py", line 855, in add_item
    item = self.index_item(item)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/item.py", line 880, in index_item
    item = self.manage_conflict(item, name)
  File "/usr/lib/python2.6/site-packages/Shinken-2.2-py2.6.egg/shinken/objects/item.py", line 788, in manage_conflict
    item.configuration_warnings.append(mesg)
AttributeError: 'Discoveryrule' object has no attribute 'configuration_warnings'
````

**Comment by geektophe** [comment]
Could you give us a configuration sample, in order see where it could come from ?

I also see you're using shinken 2.2, could you try with latest version ? (2.4.2)

**Comment by naparuba** [comment]
No update I close.
