### ISSUE TITLE
Error after installing shinken 2.04 in debian jessie

### ISSUE THREAD

**Issue by abdelbassit** [naparuba/shinken#1773]
I install shinken 2.04, when I go to restart the service it turns me this error:

[1449503242] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1449503242] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1449503242] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1449503242] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 609, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 369, in load_config_file
    self.conf.explode()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1468, in explode
    self.triggers)
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/service.py", line 1819, in explode
    if host and host.is_excluded_for(service):
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/host.py", line 909, in is_excluded_for
    return self.is_excluded_for_sdesc(service.service_description, service.is_tpl())
AttributeError: service_description

Traceback (most recent call last):
  File "/usr/bin/shinken-arbiter", line 130, in <module>
    main()
  File "/usr/bin/shinken-arbiter", line 122, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 609, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 369, in load_config_file
    self.conf.explode()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1468, in explode
    self.triggers)
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/service.py", line 1819, in explode
    if host and host.is_excluded_for(service):
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/host.py", line 909, in is_excluded_for
    return self.is_excluded_for_sdesc(service.service_description, service.is_tpl())
AttributeError: service_description

¿Any help?

Thank you

**Comment by olivierHa** [comment]
Hello,

You need to paste your configuration file. By the way, which version of
shinken are you using ? 2.04 seems strange.

Olivier

2015-12-07 16:53 GMT+01:00 abdelbassit <notifications@github.com>:

**Comment by abdelbassit** [comment]
Hello Olivier,

The shinken version is 2.4 and the erros its appear when I add specific service in services (in /etc/shinken/services).

And the error is that:

[1449593629] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1449593629] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1449593629] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1449593629] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 609, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 369, in load_config_file
    self.conf.explode()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1468, in explode
    self.triggers)
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/service.py", line 1819, in explode
    if host and host.is_excluded_for(service):
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/host.py", line 909, in is_excluded_for
    return self.is_excluded_for_sdesc(service.service_description, service.is_tpl())
AttributeError: service_description

It seems that something is not working correctlly when you play with services.

I as a test I delete all my specific services from the services file and it working well, but I need to use it to specific service.

Any suggestion?

Regards.

**Comment by abdelbassit** [comment]
Hello,

I detect the error:

The error was in my specific configuration service, I added one service Alarm without "service_description", In the other shinken version it worked without problem , but with 2.4 it doesn't work.

My specific service was as follows:

define service{
        use                     generic-service
        host_name            router.server
        check_command           check_ping!200.0,20%!600.0,60%
}

I add service_description and is working well now.


Thank you!

**Comment by olivierHa** [comment]
I am closing, glad this is working
