### ISSUE TITLE
Arbiter dies with Message: Bad HTTP/0.9 request type ('l_commands?')

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [naparuba/shinken#1810]
Hi,

My shinken installation is pretty unstable - arbiter dies once/twice a day.  It's Debian Jessie, and shinken 2.4.2 installed with pip.

I'm monitoring about 30 hosts with ~30 services on each. Installation on 1 server, no spare daemons.

Modules which I use:
- webui2
- auth-cfg-password
- mongo-logs (doesn't work wth pymongo 2.x) - at this moment off, because I keep pymongo 2.7
- retention-mongodb (doesn't work with pymongo 3.x)

My shinken.cfg is default

Not sure if it's releated, but I also have same problems as in #1594 and #1659

List of pip installed packages:
```
argparse (1.2.1)
arrow (0.4.4)
bottle (0.12.7)
bpython (0.12)
chardet (2.3.0)
colorama (0.3.2)
defusedxml (0.4.1)
docutils (0.12)
html (1.16)
html5lib (0.999)
iotop (0.6)
Pillow (2.6.1)
pip (1.5.6)
pycrypto (2.6.1)
pycurl (7.19.5)
Pygments (2.0.1)
python-apt (0.9.3.12)
python-dateutil (2.2)
python-debian (0.1.27)
python-debianbts (1.11)
PyYAML (3.11)
reportbug (6.6.3)
requests (2.4.3)
roman (2.0.0)
setuptools (5.5.1)
Shinken (2.4.2)
six (1.8.0)
slacker (0.9.0)
SOAPpy (0.12.22)
urllib3 (1.9.1)
wsgiref (0.1.2)
wstools (0.4.3)

```

Other packages/requirements were installed from Debian Jessie repository

Error message from logs:

```
[1454666553] ERROR: [Shinken] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad HTTP/0.9 request type ('l_commands?').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

[1454666553] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1454666553] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1454666553] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1454666553] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 629, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 665, in do_loop_turn
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 830, in run
    self.get_external_commands_from_satellites()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 237, in get_external_commands_from_satellites
    new_cmds = sat.get_external_commands()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/satellitelink.py", line 387, in get_external_commands
    tab = self.con.get('get_external_commands', wait='long')
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_client.py", line 139, in get
    raise Exception('Connection error to %s : %s' % (self.uri, r))
Exception: Connection error to http://localhost:7769/ : 0

```

Arbiter restart is enough to make it work again.

**Comment by TomaszUrugOlszewski** [comment]
Today it's little different error message:
```
1454909596] ERROR: [Shinken] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

[1454909596] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1454909596] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1454909596] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1454909596] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 629, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 665, in do_loop_turn
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 830, in run
    self.get_external_commands_from_satellites()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 237, in get_external_commands_from_satellites
    new_cmds = sat.get_external_commands()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/satellitelink.py", line 386, in get_external_commands
    self.con.get('ping')
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_client.py", line 139, in get
    raise Exception('Connection error to %s : %s' % (self.uri, r))
Exception: Connection error to http://localhost:7769/ : 0
```

**Comment by olivierHa** [comment]
Hello, 

Could you check paste all the daemons logs ?

Regards

Olivier

**Comment by yattamax** [comment]
Me too .... sameb problem and same OS

**Comment by yattamax** [comment]
Me too .... same problem and same OS 

`1453991239] ERROR: [Shinken] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad HTTP/0.9 request type ('l_commands?').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

[1453991239] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1453991239] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1453991239] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1453991239] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 629, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 665, in do_loop_turn
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 830, in run
    self.get_external_commands_from_satellites()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 237, in get_external_commands_from_satellites
    new_cmds = sat.get_external_commands()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/satellitelink.py", line 387, in get_external_commands
    tab = self.con.get('get_external_commands', wait='long')
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_client.py", line 139, in get
    raise Exception('Connection error to %s : %s' % (self.uri, r))
Exception: Connection error to http://localhost:7769/ : 0`

**Comment by yattamax** [comment]
Me too .... same problem and same OS 

<pre>
[1453991239] ERROR: [Shinken] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad HTTP/0.9 request type ('l_commands?').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

[1453991239] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1453991239] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1453991239] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1453991239] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 629, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 333, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 665, in do_loop_turn
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 830, in run
    self.get_external_commands_from_satellites()
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 237, in get_external_commands_from_satellites
    new_cmds = sat.get_external_commands()
  File "/usr/local/lib/python2.7/dist-packages/shinken/objects/satellitelink.py", line 387, in get_external_commands
    tab = self.con.get('get_external_commands', wait='long')
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_client.py", line 139, in get
    raise Exception('Connection error to %s : %s' % (self.uri, r))
Exception: Connection error to http://localhost:7769/ : 0
</pre>

**Comment by yattamax** [comment]
I try to add an "except"
in /usr/local/lib/python2.7/dist-packages/shinken/objects/satellitelink.py at line 400

from:
<pre>
def get_external_commands(self):
        if self.con is None:
            self.create_connection()

        # If the connection failed to initialize, bail out
        if self.con is None:
            return []

        try:
            self.con.get('ping')
            tab = self.con.get('get_external_commands', wait='long')
            tab = cPickle.loads(str(tab))
            # Protect against bad return
            if not isinstance(tab, list):
                self.con = None
                return []
            return tab
        except HTTPExceptions, exp:
            self.con = None
            return []
        except AttributeError:
            self.con = None
            return []
</pre>

TO

<pre>
def get_external_commands(self):
        if self.con is None:
            self.create_connection()

        # If the connection failed to initialize, bail out
        if self.con is None:
            return []

        try:
            self.con.get('ping')
            tab = self.con.get('get_external_commands', wait='long')
            tab = cPickle.loads(str(tab))
            # Protect against bad return
            if not isinstance(tab, list):
                self.con = None
                return []
            return tab
        except HTTPExceptions, exp:
            self.con = None
            return []
        except AttributeError:
            self.con = None
            return []
        except:
            self.con = None
            return []
</pre>

**Comment by yattamax** [comment]
UPDATE:
my small addition seems to work without problems :)

**Comment by TomaszUrugOlszewski** [comment]
Today broker died with same error message

**Comment by yattamax** [comment]
even with my change?

**Comment by TomaszUrugOlszewski** [comment]
No, I didn't update application code.

**Comment by olivierHa** [comment]
Hello,
@yattamax  I've commited your patch.
It makes the arbiter stronger.
But why the external commands return a 40x is a mystery ...

**Comment by TomaszUrugOlszewski** [comment]
After upgrading pycurl to latest version (installed with pip) problem didn't occur anymore.

**Comment by olivierHa** [comment]
I am closing this issue.
I will add a requirements for not using pycurl packages in Jessie.
Thanks

**Comment by blackrez** [comment]
I have the same error and pycurl installed from pip with the same version of Debian.
I really don't understand how this happened.

How I can help to solve this?
