### ISSUE TITLE
tried to create multiple schedulers, got a traceback

### ISSUE THREAD

**Issue by grinapo** [naparuba/shinken#1819]
I'm familiarising with shinken. Got distributed poller by the doc, works fine.
The doc is, khm, sparse about how to do that with the scheduler. So by guesswork I have started a scheduler on node2 on a pub address and told master:
define scheduler {
        scheduler_name  scheduler2
        address         node2
        port            7768
}

This resulted on node2:
```
2016-03-08 17:02:17,972 [1457452937] Info :    New configuration received
2016-03-08 17:02:17,975 [1457452937] Critical : I got an unrecoverable error. I have to exit
2016-03-08 17:02:17,975 [1457452937] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
2016-03-08 17:02:17,977 [1457452937] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 479, in main
    self.do_mainloop()
  File "/usr/lib/python2.7/dist-packages/shinken/daemon.py", line 322, in do_mainloop
    self.do_loop_turn()
  File "/usr/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 331, in do_loop_turn
    self.setup_new_conf()
  File "/usr/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 347, in setup_new_conf
    conf = cPickle.loads(conf_raw)
  File "/usr/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.__new__(X): X is not a type object (classobj)', <function _reconstructor at 0x7f34c2e4fb18>, (<class shinken.daterange.StandardDaterange at 0x7f34c0c52e88>, <ty
pe 'object'>, None))
```

**Comment by grinapo** [comment]
It could be a dependency as well, it isn't clear what is absolutely required to run scheduler only; I'm using the debian packages. (Possibly not a dependency problem since now I have installed everything just to make it sure...)
