### ISSUE TITLE
KeyError: 'proxy_socks5'

### ISSUE THREAD

**Issue by hahahafr** [naparuba/shinken#1857]
`# shinken update livestatus`

    Grabbing : livestatus
    Traceback (most recent call last):
      File "/usr/bin/shinken", line 551, in <module>
        main()
      File "/usr/bin/shinken", line 547, in main
        CLI.one_loop(command_args)
      File "/usr/bin/shinken", line 318, in one_loop
        f(*cmd_args, **cmd_opts.__dict__)
      File "/var/lib/shinken/cli/shinkenio/cli.py", line 605, in do_update
        raw = grab_package(pname)
      File "/var/lib/shinken/cli/shinkenio/cli.py", line 322, in grab_package
        proxy_socks5 = CONFIG['shinken.io']['proxy_socks5']
    KeyError: 'proxy_socks5'

I used latest github master version of **cli/shinkenio/cli.py** and **bin/shinken**.

After commenting all lines in cli.py containing "socks5" it looks like it works.
I tried to read the source code but I don't understand why "proxy_socks5" gives an error and not "proxy".

**Comment by olivierHa** [comment]
Hello, 

It works for "proxy" because there is a line "proxy=" in the shinken.ini file.

Fix incoming.
