### ISSUE TITLE
"python setup.py install" failed when directories dont exist

### ISSUE THREAD

**Issue by ajtag** [naparuba/shinken#1888]
Installed /usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg
Processing dependencies for Shinken==2.4.3
Finished processing dependencies for Shinken==2.4.3
Changing owner of /etc/shinken to shinken:shinken
Traceback (most recent call last):
  File "setup.py", line 477, in <module>
    recursive_chown(p, uid, gid, user, group)
  File "setup.py", line 112, in recursive_chown
    os.chown(path, uid, gid)
OSError: [Errno 2] No such file or directory: '/etc/shinken'

**Comment by arber1** [comment]
I have this problem too.

**Comment by anleg** [comment]
Hello,

You may have tried to re-install Shinken.
When you install it, this log may appear :
```
Previous Shinken lib detected (/usr/local/lib/python2.7/dist-packages/shinken/__init__.pyc)
```
It means that an old Shinken it detected and the installation doesn't copy the /etc/shinken directory (in order not to delete your configuration).
If it's the first installation and not an upgrade, you can try to remove this file and re-try your installation.

**Comment by arber1** [comment]
Yes i tried the re-installation but cant find path `/etc/shinken`

**Comment by ajtag** [comment]
I believe that was the first time I had installed shinken, 

as a work around i created the directory /etc/shinken and all was fine after that
