### ISSUE TITLE
ERROR: [Shinken] Worker '286' exit with an unmanaged exception 

### ISSUE THREAD

**Issue by nikotor** [naparuba/shinken#1891]
Hi !
I use Shinken 2.4.3 on CentOS 6.8 with Python 2.6. I have this error on the poller many hours after the Poller and the Scheduler were launched. If I restart the scheduler, the poller seems to work.
These are my event log messages : 

Poller.log 
```
[1487026745] INFO: [Shinken] [poller-master] Allocating new fork Worker: 1647
[1487026745] INFO: [Shinken] Cleaning BrokHandler <shinken.log.BrokHandler instance at 0xf10fc8> from logger.handlers..
[1487026802] ERROR: [Shinken] Worker '286' exit with an unmanaged exception : Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 234, in work
    self.do_work(s, returns_queue, c)
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 279, in do_work
    self.launch_new_checks()
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 175, in launch_new_checks
    r = chk.execute()
  File "/usr/lib/python2.6/site-packages/shinken/action.py", line 124, in execute
    return self.execute__()  # OS specific part
  File "/usr/lib/python2.6/site-packages/shinken/action.py", line 306, in execute__
    preexec_fn=os.setsid)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
TypeError: execve() arg 3 contains a non-string value
[1486713859] WARNING: [Shinken] [poller-master] The worker 1647 goes down unexpectedly!
```

Scheduler.log
`[1487009753] WARNING: [Shinken] 4 actions never came back for the satellite 'poller-master'.I reenable them for polling`

I didn't change my configuration and all daemons are running on the same host. Is somebody can help me ? 
Thanks !

**Comment by nikotor** [comment]
The output "ERROR - Plugin Timed Out" caused the issue.

**Comment by nikotor** [comment]
The error ouput "CRITICAL - Plugin Timed Out" generate in its env a NULL bytes '\x00' in the environment variable (which is a dictionnary). The key is either in NAGIOS_LONGHOSTOUTPUT or NAGIOS_LONGSERVICEOUTPUT. It's a non-string value that create en ERROR when Shinken attempt to create a subprocess.

```
[1487026802] ERROR: [Shinken] Worker '286' exit with an unmanaged exception : Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 234, in work
    self.do_work(s, returns_queue, c)
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 279, in do_work
    self.launch_new_checks()
  File "/usr/lib/python2.6/site-packages/shinken/worker.py", line 175, in launch_new_checks
    r = chk.execute()
  File "/usr/lib/python2.6/site-packages/shinken/action.py", line 124, in execute
    return self.execute__()  # OS specific part
  File "/usr/lib/python2.6/site-packages/shinken/action.py", line 306, in execute__
    preexec_fn=os.setsid)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
TypeError: execve() arg 3 contains a non-string value
```

To fix the issue, I add some lines in action.py.

```
def execute(self):
    """
    Start this action command. The command will be executed in a
    subprocess.
    """

    self.status = 'launched'
    self.check_time = time.time()
    self.wait_time = 0.0001
    self.last_poll = self.check_time
    # Get a local env variables with our additional values
    self.local_env = self.get_local_environnement()

    if 'NAGIOS_LONGHOSTOUTPUT' in self.local_env:
            if self.local_env['NAGIOS_LONGHOSTOUTPUT'] == '\x00':
                    self.local_env['NAGIOS_LONGHOSTOUTPUT'] = ''
    if 'NAGIOS_LONGSERVICEOUTPUT' in self.local_env:
            if  self.local_env['NAGIOS_LONGSERVICEOUTPUT'] == '\x00':
                    self.local_env['NAGIOS_LONGSERVICEOUTPUT'] = ''

    # Initialize stdout and stderr. we will read them in small parts
    # if the fcntl is available
    self.stdoutdata = ''
    self.stderrdata = ''

    return self.execute__()  # OS specific part
```
