### ISSUE TITLE
Can’t install 2.4.3

### ISSUE THREAD

**Issue by M4rotte** [naparuba/shinken#1927]
Hi,

I’ve been able to install this version some days ago (see other issues…) but then I tried to do the installation process from beginning and now the scheduler refuses to start with the following message :

```
[1503418339] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1503418339] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1503418339] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1503418339] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 542, in main
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemon.py", line 341, in do_mainloop
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 342, in do_loop_turn
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 382, in setup_new_conf
ImportError: No module named config
```

During the previous (working) installation I installed some Python modules using pip (but I can’t remember which ones…), today I tried with installing them from the Debian packages manager…

I then run `python setup.py install` from the repository. Is it the right method?

I also tried to install Shinken using pip with `pip install shinken` but it raises the same error.

Now on, if I `pip uninstall shinken` then installing it again (whatever method) it doesn’t even copy the config files in /etc/shinken (?!)

I hope somebody can help me on this… Shinken looks great on the paper but I must admit that the installation process tempers my expectations :(

Best regards.

**Comment by hvad** [comment]
Hi,

Do you install requirements (pip install -r requirements.txt) ? 

Best regards

**Comment by M4rotte** [comment]
I just tried, I still have the same error. The scheduler is starting but it fails on:

```
[1503480720] INFO: [Shinken] Waiting for initial configuration
[1503480747] INFO: [Shinken] New configuration received
[1503480747] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1503480747] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1503480747] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1503480747] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 542, in main
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemon.py", line 341, in do_mainloop
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 342, in do_loop_turn
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/schedulerdaemon.py", line 382, in setup_new_conf
ImportError: No module named config
```

as soon as it receives its configuration.

**Comment by naparuba** [comment]
No more named config seems like the python is lost about the shinken librairy.

Did this installation was from a scratch os without previous shinken instal try? Setup multiple time with multiple installs (setup.py/pip/yum) will just fail in the end, because there will be version mix every where.

**Comment by M4rotte** [comment]
No there was previous shinken install. That’s probably the right explanation. Do you know how I can "reset" the pip setup?

**Comment by M4rotte** [comment]
I tried again. Still have the same "ImportError: No module named config".

When I run "python setup.py install" it installs shinken in /usr/**local**/lib/python2.7/dist-packages/

I guess I should install it in /usr/lib/python2.7/dist-packages/ instead.

The source is in /usr/local/src/shinken

A help message, when I run the setup.py script, makes reference to a _-d_ or _--install-dir_ but it seems there is no such option. There is a "--root" option but it’s not helpful.

What I understand is that shinken is getting installed in /usr/local/ but all the python stuff (installed by apt or pip) is located in /usr

I will try to install shinken with the source in /usr/src to see if it helps.

**Comment by M4rotte** [comment]
Not sure how to fix my problem and I didn’t try again yet. But as this bug is obviously due to me being a complete newbie with Python environments I close it.

**Comment by sachaw0lf** [comment]
> I tried again. Still have the same "ImportError: No module named config".
> 
> When I run "python setup.py install" it installs shinken in /usr/**local**/lib/python2.7/dist-packages/
> 
> I guess I should install it in /usr/lib/python2.7/dist-packages/ instead.
> 
> The source is in /usr/local/src/shinken
> 
> A help message, when I run the setup.py script, makes reference to a _-d_ or _--install-dir_ but it seems there is no such option. There is a "--root" option but it’s not helpful.
> 
> What I understand is that shinken is getting installed in /usr/local/ but all the python stuff (installed by apt or pip) is located in /usr
> 
> I will try to install shinken with the source in /usr/src to see if it helps.

Hi M4rotte,
I tried to install SHINKEN 2.4 on my Debian Stretch and I have the same issue. 
Did you solved it ? 
All the files are stored in /usr/local/lib/python2.7/dist-packages/ and i don't understand why they are not copied to the correct folders.
Many Thanks
