### ISSUE TITLE
scheduler registering error

### ISSUE THREAD

**Issue by charlyhue** [naparuba/shinken#1933]
Hello,
Since yesterday (after centos update) my shinken instance doesn't restart. I have this stacktrace in the scheduler log:
```
scheduler_1      | Registering get_raw_stats [] <shinken.daemons.schedulerdaemon.IStats object at 0x7fccfa0fde50>
scheduler_1      | .Traceback (most recent call last):
scheduler_1      |   File "/usr/lib/python2.7/site-packages/shinken/webui/bottlecore.py", line 688, in _handle
scheduler_1      |     return callback(**args)
scheduler_1      |   File "/usr/lib/python2.7/site-packages/shinken/webui/bottlecore.py", line 1359, in wrapper
scheduler_1      |     rv = callback(*a, **ka)
scheduler_1      |   File "/usr/lib/python2.7/site-packages/shinken/http_daemon.py", line 371, in f_wrapper
scheduler_1      |     v = zlib.decompress(v)
scheduler_1      | error: Error -5 while decompressing data: incomplete or truncated stream
scheduler_1      | Traceback (most recent call last):
scheduler_1      |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
scheduler_1      |     self.finish_response()
scheduler_1      |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
scheduler_1      |     self.write(data)
scheduler_1      |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
scheduler_1      |     self.send_headers()
scheduler_1      |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 271, in send_headers
scheduler_1      |     self._write(str(self.headers))
scheduler_1      |   File "/usr/lib/python2.7/socket.py", line 328, in write
scheduler_1      |     self.flush()
scheduler_1      |   File "/usr/lib/python2.7/socket.py", line 307, in flush
scheduler_1      |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
scheduler_1      | error: [Errno 104] Connection reset by peer
scheduler_1      | Traceback (most recent call last):
scheduler_1      |   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
scheduler_1      |     self.process_request(request, client_address)
scheduler_1      |   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
scheduler_1      |     self.finish_request(request, client_address)
scheduler_1      |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
scheduler_1      |     self.RequestHandlerClass(request, client_address, self)
scheduler_1      |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
scheduler_1      |     self.finish()
scheduler_1      |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
scheduler_1      |     self.wfile.close()
scheduler_1      |   File "/usr/lib/python2.7/socket.py", line 283, in close
scheduler_1      |     self.flush()
scheduler_1      |   File "/usr/lib/python2.7/socket.py", line 307, in flush
scheduler_1      |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
scheduler_1      | error: [Errno 32] Broken pipe
scheduler_1      | ----------------------------------------
scheduler_1      | Exception happened during processing of request from ('172.18.0.10', 40968)
scheduler_1      | ----------------------------------------
```
And the arbiter say:
```
[1508334932] ERROR: [Shinken] Failed sending configuration for scheduler-master: Connection error to http://scheduler:7768/ : The requested URL returned error: 500 Internal Server Error
```

**Comment by geektophe** [comment]
Sorry for my late answer. I don't know if you still have the issue....

It seems the communication abruptly shuts down between your services. Did you check your hosts correctly communicate ? (ping test, iperf, etc...)

What upgrade did you perform ? A simple package update, or did you upgrade the whole distribution to a new release ?
