### ISSUE TITLE
Broker module crash with a python exception

### ISSUE THREAD

**Issue by Touchedegris** [naparuba/shinken#1939]
Hi,
I have an installation on a Ubuntu 16.04.3 LTS server installed from PIP. All services are running on a single machine.

In my broker configuration, I loaded webui2 and influxdb.

At about every 5 hours, my broker module crashes with the folloeing error:
[1516075608] WARNING: [broker-master] Connection problem to the reactionner reactionner-master: Connection error to http://localhost:7769/ : Operation timed out after 120001 milliseconds with 0 bytes received
[1516075609] INFO: [broker-master] Connection OK to the reactionner reactionner-master
[1516076182] ERROR: [broker-master] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>
[1516076182] ERROR: [broker-master] Connection error to http://localhost:7769/ : 0
[1516076182] ERROR: [broker-master] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/brokerdaemon.py", line 328, in get_new_broks
    con.get('ping')
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_client.py", line 139, in get
    raise Exception('Connection error to %s : %s' % (self.uri, r))
Exception: Connection error to http://localhost:7769/ : 0

I need to restart it manually to get data sent back to my influx database.

Can you help me find out what is the reason of this crash?

Please note that I get many "connection error" on localhost connections between daemons (broker, poller, scheduler) that I can't explain as they are running all on the same server.

**Comment by geektophe** [comment]
Hi, sorry for the delay.

Perhaps is there some contention in one of the internal messages queues.

Could you tell us how many checks you're running, and what's the memory usage on the machine running the shinken services ?

**Comment by Touchedegris** [comment]
No worries 😊

I have about 70 checks now but it was more around 40 at the time I raised the issue.  As a temporary solution, I have commented the line 139 from /usr/local/lib/python2.7/dist-packages/shinken/http_client.py.  I still see the 400 error sometimes, but the service keeps running and it does not seem to affect my monitoring.

I did a tcpdump on the server on the loopback interface to see what packet was sent to get a 400 error, but it was not different that the previous requests.  In a standard keep-alive, I get:
GET /ping? HTTP/1.1
Host: localhost:7769
User-Agent: shinken:2.4.3 pycurl:7.47.0
Accept: */*
Keep-Alive: 300
Connection: Keep-Alive

HTTP/1.0 200 OK
Date: Thu, 25 Jan 2018 12:31:45 GMT
Server: WSGIServer/0.1 Python/2.7.12
Content-Length: 6
Content-Type: text/html; charset=UTF-8

"pong"

On the one that fails, I get this:
GET /ping? HTTP/1.1
Host: localhost:7769
User-Agent: shinken:2.4.3 pycurl:7.47.0
Accept: */*
Keep-Alive: 300
Connection: Keep-Alive

<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

I did not see anything different in both request, so the prolem seems to be more on the reactionner side.

I suspected the memory as well because I was at around 90% used so I boosted the memory.  Here is the actual memory usage:

KiB Mem :  6110844 total,  3383392 free,   710228 used,


De : Christophe Simon [mailto:notifications@github.com]
Envoyé : 5 février 2018 03:33
À : naparuba/shinken <shinken@noreply.github.com>
Cc : Touchedegris <francois_bourassa@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [naparuba/shinken] Broker module crash with a python exception (#1939)


Hi, sorry for the delay.

Perhaps is there some contention in one of the internal messages queues.

Could you tell us how many checks you're running, and what's the memory usage on the machine running the shinken services ?

**Comment by geektophe** [comment]
Thanks for the packet captures, that's exactly what wee need.

Indeed, something's strange, as if part of the request was truncated before reaching the reactionner server code...

Do you see anything strange in reactionner logs ?

Could you also tell us which version of cherrypy you're using ?

Does the problem persist now you have raised memory ?

**Comment by Touchedegris** [comment]
I cannot trace back a correlation between the 2 logs.  However I now see other 400 errors but those are related to the poller:
[1517681011] ERROR: [broker-master] There was a critical error : <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad HTTP/0.9 request type ('name=broker-master').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

[1517681011] ERROR: [broker-master] Cannot load broks data from poller-master : a2b_base64() argument 1 must be string or buffer, not None

It seems I do not have cherypy installed.  I installed Shinken using the pip method.  Should it be installed?

After upgrading the memory, I had a few crashes so I assumed it did not resolve the issue.  Now I still see a couple of 400 errors, but I am not sure they are related to the reactionner as the exception is not raised.

**Comment by geektophe** [comment]
I forgot there was a bug related to an uncaught exception in the http client here: #1897. I published a PR to fix this here: #1919.

Do you have such a patch in the release you're using ? If not so, could you try to apply it and see if there's still some crashes ?
