### ISSUE TITLE
est-il possible d'installer webui sans le code sources (sans internet)

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1953]
Bonjour j'ai réussi à installer shinken à partir d'un fichier que j'ai décompressé localement puis transférer sur le serveur.
quand j'arrive au niveau l'installation du module webui j'ai ces erreurs.
Je voudrais installer webui2 sans le code sources SVP.

[shinken@h1l1echc1h shinken-2.4.3]$ shinken search webui
[1527681427] ERROR: [Shinken] There was a critical error : (28, 'Connection timed out after 30001 milliseconds')
Traceback (most recent call last):
  File "/bin/shinken", line 541, in <module>
    main()
  File "/bin/shinken", line 537, in main
    CLI.one_loop(command_args)
  File "/bin/shinken", line 317, in one_loop
    f(*cmd_args, **cmd_opts.__dict__)
  File "/var/lib/shinken/cli/shinkenio/cli.py", line 231, in do_search
    print_search_matches(matches)
  File "/var/lib/shinken/cli/shinkenio/cli.py", line 194, in print_search_matches
    if len(matches) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by hvad** [comment]
Oui en téléchargeant l'archive.
