### ISSUE TITLE
Attempt to restart Shinken fails

### ISSUE THREAD

**Issue by bernd-wechner** [naparuba/shinken#1959]
I'm following this excellent tutorial:

http://shinkenlab.io/online-course-1-installation/

I got almost to the end without drama, very sweet. But then this last step:

> Great :) Now you can restart shinken and tail your shinken logs to wait for some alerts:

causes me dramas!

```
$ /etc/init.d/shinken restart
Restarting scheduler
 * FAILED: AttributeError: 'module' object has no attribute 'SSL_ST_INIT' (full output is in /tmp/bad_start_for_scheduler)
   ...fail!
Restarting poller
 * FAILED: AttributeError: 'module' object has no attribute 'SSL_ST_INIT' (full output is in /tmp/bad_start_for_poller)
   ...fail!
Restarting reactionner
 * FAILED: AttributeError: 'module' object has no attribute 'SSL_ST_INIT' (full output is in /tmp/bad_start_for_reactionner)
   ...fail!
Restarting broker
 * FAILED: AttributeError: 'module' object has no attribute 'SSL_ST_INIT' (full output is in /tmp/bad_start_for_broker)
   ...fail!
Restarting receiver
 * FAILED: AttributeError: 'module' object has no attribute 'SSL_ST_INIT' (full output is in /tmp/bad_start_for_receiver)
   ...fail!
Restarting arbiter
Doing config check
 * full result is in /tmp/shinken_checkconfig_result
 * ConfigCheck failed: AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
   ...fail!
```

Looking into one of the bad_start files:

```
$ cat /tmp/bad_start_for_scheduler
Traceback (most recent call last):
  File "/usr/bin/shinken-scheduler", line 107, in <module>
    from shinken.daemons.schedulerdaemon import Shinken
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/schedulerdaemon.py", line 36, in <module>
    from shinken.daemon import Daemon
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemon.py", line 49, in <module>
    import shinken.http_daemon
  File "/usr/local/lib/python2.7/dist-packages/shinken/http_daemon.py", line 45, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

which seems a code issue. Perhaps an SSL package version issue. Any clues as to why this happens or how to fix it?

**Comment by bernd-wechner** [comment]
Solved it. Spoke too soon. Answer was here:

https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init#43267158

and all I did was the recommended:

`sudo python -m easy_install --upgrade pyOpenSSL`

And now:

```
$ sudo /etc/init.d/shinken restart
Restarting scheduler
   ...done.
Restarting poller
   ...done.
Restarting reactionner
   ...done.
Restarting broker
   ...done.
Restarting receiver
   ...done.
Restarting arbiter
Doing config check
   ...done.
   ...done.
```

**Comment by geektophe** [comment]
Thanks for the feedback :)
