### ISSUE TITLE
shinken 2.4.3 getting IndexError: string index out of range error

### ISSUE THREAD

**Issue by bhanubteja** [naparuba/shinken#1966]
While starting shinken getting the below error
```
^[[93m[1533751016] WARNING: [Shinken] Guessing the property  type because it is not in Config object properties^[[0m
^[[95m[1533751016] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.^[[0m
^[[95m[1533751016] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken^[[0m
^[[95m[1533751016] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README^[[0m
^[[95m[1533751016] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 619, in main
    self.load_config_file()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 281, in load_config_file
    raw_objects = self.conf.read_config_buf(buf)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1050, in read_config_buf
    self.load_params(params)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 848, in load_params
    if key[0] == '$' and key[-1] == '$':
IndexError: string index out of range
^[[0m
Traceback (most recent call last):
  File "/usr/bin/shinken-arbiter", line 130, in <module>
    main()
  File "/usr/bin/shinken-arbiter", line 122, in main
    daemon.main()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 619, in main
    self.load_config_file()
  File "/usr/lib/python2.7/site-packages/shinken/daemons/arbiterdaemon.py", line 281, in load_config_file
    raw_objects = self.conf.read_config_buf(buf)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 1050, in read_config_buf
    self.load_params(params)
  File "/usr/lib/python2.7/site-packages/shinken/objects/config.py", line 848, in load_params
    if key[0] == '$' and key[-1] == '$':
IndexError: string index out of range
```

Thanks in advance

**Comment by s-dewailly** [comment]
Hi, 

We recently have this error un two cases : 
- a duplicate without $ correctly set around values
- a macro without $ correctly set 

Hope that will help.
Serge

**Comment by bhanubteja** [comment]
Hello Serge,

Could you help me resolving this issue in detail.

**Comment by geektophe** [comment]
Do you have more context to provide us with ?

Do you have the configuration object it crashed on ?  You should have the configuration file that contains the error just above the error message. 

Example:

    [1541505050] INFO: [Shinken] Processing object config file 'services/tool.cfg'

The latest configuration file parsed should contain the error.

Could you double check the syntax, or paste us the (anonymized) content (if it's not too large) ?
