### ISSUE TITLE
Arbiter failled to start on windows

### ISSUE THREAD

**Issue by xynos** [naparuba/shinken#799]
Hello,

I'm trying to start the arbiter on windows 7, but it still stuck on this issue:

[1364918560] Info :    [Arbiter] Serializing the configurations...
[1364918560] Debug :   [All] Serializing the configuration 0
[1364918560] Debug :   [config] time to serialize the conf All:0 is 0.00999999046326
[1364918560] Debug :   [config] time to serialize the global conf : 0.0139999389648
[1364918560] Info :    Configuration Loaded
[1364918560] Warning : You can't change user on this system
[1364918560] Warning : The parallel daemon check is not available on nt
[1364918560] Info :    Initializing Pyro connection with host:localhost port:7770 ssl:False
Process Process-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\shinken\shinken\modules\named_pipe.py", line 114, in main
    self.open()
  File "C:\shinken\shinken\modules\named_pipe.py", line 78, in open
    os.mkfifo(self.pipe_path, 0660)
AttributeError: 'module' object has no attribute 'mkfifo'
[1364918561] Critical : I got an unrecoverable error. I have to exit
[1364918561] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
[1364918561] Critical : Exception trace follows: Traceback (most recent call last):
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 553, in main
    self.do_mainloop()
  File "C:\shinken\shinken\daemon.py", line 244, in do_mainloop
    self.do_loop_turn()
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 587, in do_loop_turn
    self.run()
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 684, in run
    self.dispatcher.check_alive()
  File "C:\shinken\shinken\dispatcher.py", line 121, in check_alive
    elt.update_infos()
  File "C:\shinken\shinken\satellitelink.py", line 203, in update_infos
    self.ping()
  File "C:\shinken\shinken\satellitelink.py", line 234, in ping
    self.add_failed_check_attempt(reason=str(exp))
  File "C:\shinken\shinken\satellitelink.py", line 183, in add_failed_check_attempt
    logger.warning("Add failed attempt to %s (%d/%d) %s" % (self.get_name(), self.attempt, self.max_check_attempts, reason))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 48: ordinal not in range(128)

Traceback (most recent call last):
  File "C:\shinken\bin\shinken-arbiter.py", line 111, in <module>
    daemon.main()
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 553, in main
    self.do_mainloop()
  File "C:\shinken\shinken\daemon.py", line 244, in do_mainloop
    self.do_loop_turn()
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 587, in do_loop_turn
    self.run()
  File "C:\shinken\shinken\daemons\arbiterdaemon.py", line 684, in run
    self.dispatcher.check_alive()
  File "C:\shinken\shinken\dispatcher.py", line 121, in check_alive
    elt.update_infos()
  File "C:\shinken\shinken\satellitelink.py", line 203, in update_infos
    self.ping()
  File "C:\shinken\shinken\satellitelink.py", line 234, in ping
    self.add_failed_check_attempt(reason=str(exp))
  File "C:\shinken\shinken\satellitelink.py", line 183, in add_failed_check_attempt
    logger.warning("Add failed attempt to %s (%d/%d) %s" % (self.get_name(), self.attempt, self.max_check_attempts, reason))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 48: ordinal not in range(128)

**Comment by naparuba** [comment]
we close. If someone still have an issue, he/she can reopen it.
